### ISSUE TITLE
Distinguishing between rules and rule applications

### ISSUE THREAD

**Issue by cristianolongoodhl** [ontolex/morph#24]
In the current draft version,  morph:Rule represents an _operation_. In general, operations and their applications to concrete cases are distinguished concepts. For example, 'replacing the final _o_ with _i_' is a general rule which can be applied to all masculine singuar lexical expressions of Italian to get the plural form (apologyze, I'm not really into inflectional matters). Thus, provided that a Rule represents a _kind of phenomena_ and not the occurrences of this phenomena applied to language expressions, I can't understand morph:involves.

**Comment by max-ionov** [comment]
morph:Morph elements can be thought of as operators of an operation. Then, a Rule is an operation, Morph is one of the operators and morph:involves is indicates that this particular morph is a part of this particular operation.
In your example, there is a morph with the surface form "-i" and grammatical meaning "[number=singular]". morph:involves indicates that this morph was involved in the application of this rule

**Comment by cristianolongoodhl** [comment]
great, thank you for the explainatio
