### ISSUE TITLE
property morph:grammaticalMeaning for InflectionType

### ISSUE THREAD

**Issue by pennyl67** [ontolex/morph#8]
According to discussions, this is needed for assigning grammatical features to inflectionType. This is not reflected neither in the diagram nor in the draft with the definitions.

**Comment by chiarcos** [comment]
approved by https://github.com/ontolex/morph/blob/master/doc/wrapup/minutes-2025-06-04.md (note the renaming of `InflectionType` to `InflectionSlot`)
